/**
 * Gemini Image Generation Service (Nano Banana)
 * Uses Google's Gemini API for Instagram-style image generation
 */

import { GoogleGenAI } from '@google/genai';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

export interface ImageGenerationResult {
  imagePath: string;
  text?: string;
}

/**
 * Generate an Instagram-style image using Gemini
 */
export async function generateInstagramImage(
  message: string,
  apiKey?: string
): Promise<ImageGenerationResult> {
  const key = apiKey || process.env.GOOGLE_AI_API_KEY;

  if (!key) {
    throw new Error('Google AI API key not found. Set GOOGLE_AI_API_KEY in your .env file.');
  }

  const ai = new GoogleGenAI({ apiKey: key });

  const prompt = `Create a visually stunning Instagram-style image post for the following message.
The image should be:
- Eye-catching and professional
- Have a modern, aesthetic design
- Include the text message prominently displayed in a stylish way
- Use appealing colors and typography
- Look like a high-quality social media graphic

Message to visualize: "${message}"

Generate the image with the text beautifully integrated into the design.`;

  const response = await ai.models.generateContent({
    model: 'gemini-3-pro-image-preview',
    contents: prompt,
    config: {
      responseModalities: ['TEXT', 'IMAGE'],
    },
  });

  const result: ImageGenerationResult = {
    imagePath: '',
  };

  // Process response parts
  if (response.candidates && response.candidates[0]?.content?.parts) {
    for (const part of response.candidates[0].content.parts) {
      if (part.text) {
        result.text = part.text;
      } else if (part.inlineData && part.inlineData.data) {
        // Save image to temp file
        const tempDir = os.tmpdir();
        const imagePath = path.join(tempDir, `gemini-image-${Date.now()}.png`);
        const buffer = Buffer.from(part.inlineData.data, 'base64');
        fs.writeFileSync(imagePath, buffer);
        result.imagePath = imagePath;
      }
    }
  }

  if (!result.imagePath) {
    throw new Error('No image was generated by Gemini');
  }

  return result;
}

/**
 * Check if Gemini API is configured
 */
export function isGeminiConfigured(): boolean {
  return !!process.env.GOOGLE_AI_API_KEY;
}
